### ISSUE TITLE
File duplicate causes an exception instead of being skipped

### ISSUE THREAD

**Issue by hashar** [amire80/commons_upload#10]
After screenshots have been taken, if I run the script again it bails out because the files are duplicates:
```
exec bundle exec rake commons_upload

MediawikiApi::ApiError: The upload is an exact duplicate of the current version of [[:File:VisualEditor insert table-ast.png]]. (fileexists-no-change)
/cache/bundle/ruby/2.3.0/gems/mediawiki_api-0.7.1/lib/mediawiki_api/client.rb:211:in `send_request'
/cache/bundle/ruby/2.3.0/gems/mediawiki_api-0.7.1/lib/mediawiki_api/client.rb:232:in `raw_action'
/cache/bundle/ruby/2.3.0/gems/mediawiki_api-0.7.1/lib/mediawiki_api/client.rb:36:in `action'
/cache/bundle/ruby/2.3.0/gems/mediawiki_api-0.7.1/lib/mediawiki_api/client.rb:166:in `upload_image'
/cache/bundle/ruby/2.3.0/gems/commons_upload-1.0.1/lib/commons_upload.rb:34:in `image'
/cache/bundle/ruby/2.3.0/gems/commons_upload-1.0.1/lib/commons_upload.rb:45:in `block in images'
/cache/bundle/ruby/2.3.0/gems/commons_upload-1.0.1/lib/commons_upload.rb:43:in `each'
/cache/bundle/ruby/2.3.0/gems/commons_upload-1.0.1/lib/commons_upload.rb:43:in `images'
/src/Rakefile:27:in `block in <top (required)>'
```

Environment:

commons_upload 1.0.1
MEDIAWIKI_API_UPLOAD_URL=https://commons.wikimedia.beta.wmflabs.org/w/api.php

The files:
https://commons.wikimedia.beta.wmflabs.org/w/index.php?title=Special:ListFiles/Hashar&ilshowall=1

There might be an API flag to ignore all errors/warnings, else the gem would have to catch the `MediawikiApi::ApiError` and print the upload has been skipped / screenshots is already present.

**Comment by hashar** [comment]
Poke @amire80 @zeljkofilipin
